package personal.xjl.jerrymouse.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import personal.xjl.jerrymouse.entity.Course;

public class CourseSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public String insertSelective(Course record) {
        BEGIN();
        INSERT_INTO("course");

        if (record.getId() != null) {
            VALUES("Id", "#{id,jdbcType=INTEGER}");
        }

        if (record.getName() != null) {
            VALUES("name", "#{name,jdbcType=VARCHAR}");
        }

        if (record.getTeacherId() != null) {
            VALUES("teacher_id", "#{teacherId,jdbcType=INTEGER}");
        }

        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Course record) {
        BEGIN();
        UPDATE("course");

        if (record.getName() != null) {
            SET("name = #{name,jdbcType=VARCHAR}");
        }

        if (record.getTeacherId() != null) {
            SET("teacher_id = #{teacherId,jdbcType=INTEGER}");
        }

        WHERE("Id = #{id,jdbcType=INTEGER}");

        return SQL();
    }
}