package personal.xjl.jerrymouse.mapper;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import personal.xjl.jerrymouse.entity.Course;
import personal.xjl.jerrymouse.entity.Score;

import java.util.List;

@Mapper
public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Delete({
            "delete from score",
            "where Id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Insert({
            "insert into score ( student_id, ",
            "course_id, score)",
            "values ( #{studentId,jdbcType=INTEGER}, ",
            "#{course_Id,jdbcType=INTEGER}, #{score,jdbcType=DOUBLE})"
    })
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @InsertProvider(type=ScoreSqlProvider.class, method="insertSelective")
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Select({
            "select",
            "Id, student_id, course_id, score",
            "from score",
            "where Id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="Id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="student_id", property="studentId", jdbcType=JdbcType.INTEGER),
            @Result(column="course_id", property="course_Id", jdbcType=JdbcType.INTEGER),
            @Result(column="score", property="score", jdbcType=JdbcType.DOUBLE)
    })
    Score selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ScoreSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated
     */
    @Update({
            "update score",
            "set student_id = #{studentId,jdbcType=INTEGER},",
            "course_id = #{course_Id,jdbcType=INTEGER},",
            "score = #{score,jdbcType=DOUBLE}",
            "where Id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Score record);

    @Select("select * from score where student_id=#{id,jdbcType=INTEGER}")
    @Results({
            @Result(column="Id", property="id", jdbcType=JdbcType.INTEGER),
            @Result(column="course_id", property="course_Id", jdbcType=JdbcType.INTEGER),
            @Result(column="student_id", property="studentId", jdbcType=JdbcType.INTEGER),
            @Result(column="course_id", property="course", javaType= Course.class,
            one=@One(select = "personal.xjl.jerrymouse.mapper.CourseMapper.selectByPrimaryKey"))
    })
    List<Score> selectByStudentId(int id);
}